### ISSUE TITLE
Organization part

### ISSUE THREAD

**Issue by TaoChen18** [MaggieNie/final_project#21]
- [ ] describe the organization
- [ ] describe the activities and responsibilities
- [ ] describe the decisions process and responsibilities
