### ISSUE TITLE
Introduction part mission

### ISSUE THREAD

**Issue by TaoChen18** [MaggieNie/final_project#6]
Including the following content:
- [x] The purpose of this documentation
- [x] Document convention
- [x] Intended audience and reading suggestions
- [x] Project scope confirmation

Make sure to check all boxes after completion.
